"""followers

Revision ID: 739b5ee9da1b
Revises: 963a5a7aee0a
Create Date: 2019-02-23 18:05:31.427833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739b5ee9da1b'
down_revision = '963a5a7aee0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
