"""new fields in user model

Revision ID: 963a5a7aee0a
Revises: e55538103709
Create Date: 2019-02-23 09:57:27.781843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963a5a7aee0a'
down_revision = 'e55538103709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
